-- GENERATED by scripts/gen-sql.mjs from examples/demo-schema.mjs — do not edit by hand.
-- Re-run `node scripts/gen-sql.mjs` after changing the schema spec.

CREATE TABLE companies (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT,
  "name"                     TEXT,
  "website"                  TEXT,
  "industry"                 TEXT,
  "employees"                REAL,
  "status"                   TEXT,
  "notes"                    TEXT,
  extra_json    TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_companies_ws ON companies(workspace_id);

CREATE TABLE contacts (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT,
  "name"                     TEXT,
  "email"                    TEXT,
  "title"                    TEXT,
  extra_json    TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_contacts_ws ON contacts(workspace_id);

CREATE TABLE deals (
  id            TEXT PRIMARY KEY,
  workspace_id  TEXT,
  "name"                     TEXT,
  "amount"                   REAL,
  "stage"                    TEXT,
  "probability"              REAL,
  "close_date"               TEXT,
  "owner"                    TEXT,
  extra_json    TEXT,
  created_at    TEXT NOT NULL DEFAULT (datetime('now')),
  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))
);
CREATE INDEX idx_deals_ws ON deals(workspace_id);

