-- GENERATED by scripts/gen-sql.mjs from examples/demo-schema.mjs — do not edit by hand.
-- Re-run `node scripts/gen-sql.mjs` after changing the schema spec.

-- One row per relation edge; both sides' link fields read this table.

CREATE TABLE link_company_contacts (
  company_id TEXT NOT NULL,   -- companies.id
  contact_id TEXT NOT NULL,   -- contacts.id
  PRIMARY KEY (company_id, contact_id)
);
CREATE INDEX idx_link_company_contacts_contact_id ON link_company_contacts(contact_id);

CREATE TABLE link_company_deals (
  company_id TEXT NOT NULL,   -- companies.id
  deal_id TEXT NOT NULL,   -- deals.id
  PRIMARY KEY (company_id, deal_id)
);
CREATE INDEX idx_link_company_deals_deal_id ON link_company_deals(deal_id);

