#!/usr/bin/env node
/**
 * Generate the entity + link migrations from examples/demo-schema.mjs (the demo
 * source of truth). Writes:
 *   packages/api/migrations/0002_entities.sql   (entity tables)
 *   packages/api/migrations/0003_links.sql      (join tables for relations)
 *
 * Run after editing the schema:
 *   node scripts/gen-sql.mjs
 *
 * The output is committed so the migrations are reviewable and deterministic.
 * 0001_meta.sql (the registry DDL) is hand-written and not generated here.
 */
import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, resolve } from "node:path";
import { TABLES, columnType, usedRelations } from "../examples/demo-schema.mjs";

const __dirname = dirname(fileURLToPath(import.meta.url));
const migrationsDir = resolve(__dirname, "../packages/api/migrations");

const HEADER = `-- GENERATED by scripts/gen-sql.mjs from examples/demo-schema.mjs — do not edit by hand.
-- Re-run \`node scripts/gen-sql.mjs\` after changing the schema spec.
`;

// Always double-quote column names so the quoting policy is single-sourced and
// matches the seeder INSERT and filter.ts SELECT (both always quote). This makes
// any future column that collides with a SQLite keyword safe by default.
const quoteCol = (name) => `"${name}"`;

// ---- 0002_entities.sql ----------------------------------------------------
let entities = HEADER + "\n";
for (const t of TABLES) {
  const cols = [];
  cols.push("  id            TEXT PRIMARY KEY"); // rec… ids
  cols.push("  workspace_id  TEXT"); // multi-tenant seam (nullable today)
  for (const fld of t.fields) {
    const sqlType = columnType(fld.type);
    if (!sqlType) continue; // link/formula/lookup are not stored as columns
    cols.push(`  ${quoteCol(fld.col).padEnd(26)} ${sqlType}`);
  }
  cols.push("  extra_json    TEXT"); // escape hatch for runtime-added fields
  cols.push("  created_at    TEXT NOT NULL DEFAULT (datetime('now'))");
  cols.push("  updated_at    TEXT NOT NULL DEFAULT (datetime('now'))");
  entities += `CREATE TABLE ${t.slug} (\n${cols.join(",\n")}\n);\n`;
  entities += `CREATE INDEX idx_${t.slug}_ws ON ${t.slug}(workspace_id);\n\n`;
}
writeFileSync(resolve(migrationsDir, "0002_entities.sql"), entities);

// ---- 0003_links.sql -------------------------------------------------------
let links = HEADER + "\n";
links += "-- One row per relation edge; both sides' link fields read this table.\n\n";
for (const r of usedRelations()) {
  links += `CREATE TABLE ${r.name} (\n`;
  links += `  ${r.a} TEXT NOT NULL,   -- ${r.aTable}.id\n`;
  links += `  ${r.b} TEXT NOT NULL,   -- ${r.bTable}.id\n`;
  links += `  PRIMARY KEY (${r.a}, ${r.b})\n`;
  links += ");\n";
  // reverse-lookup index on the second endpoint (PK already covers the first)
  links += `CREATE INDEX idx_${r.name}_${r.b} ON ${r.name}(${r.b});\n\n`;
}
writeFileSync(resolve(migrationsDir, "0003_links.sql"), links);

console.error(
  `wrote 0002_entities.sql (${TABLES.length} tables) and 0003_links.sql (${usedRelations().length} relations)`,
);
