#!/usr/bin/env node
/**
 * Emit SQL that seeds:
 *   1. the registry (meta_tables / meta_fields / meta_views) from the demo schema, and
 *   2. a handful of demo rows for each table (Companies / Contacts / Deals) plus
 *      the relation edges between them.
 *
 * Pure — no network. Idempotent for the registry (INSERT OR REPLACE); the demo
 * rows use fixed ids so re-running replaces them too.
 *
 *   node scripts/seed.mjs > /tmp/seed.sql
 *   (cd packages/api && npx wrangler d1 execute <your-db> --remote --file=/tmp/seed.sql)
 *
 * Creates sensible default views per table so the UI immediately exercises the
 * table / kanban / calendar view types.
 */
import { sqlQuote as q, TABLES } from "../examples/demo-schema.mjs";

const jsonOrNull = (o) => (o ? q(JSON.stringify(o)) : "NULL");

// Preferred single-select (Kanban) + date (Calendar) fields per table.
const KANBAN = {
  companies: "fld_70c82fef25d03b72", // Status
  deals: "fld_ab8460da74d9c748",     // Stage
};
const CALENDAR = {
  deals: "fld_6f0bae1cf3cda9f7",     // Close Date
};
// Dashboard (trend charts): a date axis + the numeric fields to plot over it.
const DASHBOARD = {
  deals: {
    dateFieldId: "fld_6f0bae1cf3cda9f7", // Close Date
    metricFieldIds: ["fld_32535ebf764c27b1", "fld_89ae4f65c5851cc6"], // Amount, Probability
  },
};

const out = [];
out.push("-- GENERATED by scripts/seed.mjs — registry + demo data for gridbase.");

// ---- registry ------------------------------------------------------------
TABLES.forEach((t, ti) => {
  out.push(
    `INSERT OR REPLACE INTO meta_tables (table_id, workspace_id, name, slug, primary_field_id, position, source_kind, source_ref) ` +
      `VALUES (${q(t.id)}, NULL, ${q(t.name)}, ${q(t.slug)}, ${q(t.primaryFieldId)}, ${ti}, 'd1', NULL);`,
  );

  t.fields.forEach((fld, fi) => {
    let options = null;
    if (fld.type === "select" || fld.type === "multiselect") options = fld.options ?? null;
    else if (fld.type === "link") options = fld.options ?? null;
    else if (fld.type === "formula") options = fld.options ?? null;
    else if (fld.type === "lookup") options = fld.options ?? null;
    else if (fld.options) options = fld.options;

    const noColumn = fld.type === "link" || fld.type === "formula" || fld.type === "lookup";
    const columnName = noColumn ? null : fld.col;
    const isComputed = fld.type === "formula" || fld.type === "lookup" ? 1 : 0;
    const isPrimary = fld.id === t.primaryFieldId ? 1 : 0;

    out.push(
      `INSERT OR REPLACE INTO meta_fields (field_id, table_id, name, type, column_name, position, options, is_computed, is_primary) ` +
        `VALUES (${q(fld.id)}, ${q(t.id)}, ${q(fld.name)}, ${q(fld.type)}, ${columnName ? q(columnName) : "NULL"}, ${fi}, ${jsonOrNull(options)}, ${isComputed}, ${isPrimary});`,
    );
  });

  // Default views.
  const view = (suffix, name, type, config, pos) =>
    out.push(
      `INSERT OR REPLACE INTO meta_views (view_id, table_id, name, type, position, is_hidden, config) ` +
        `VALUES ('viw_${t.slug}_${suffix}', ${q(t.id)}, ${q(name)}, ${q(type)}, ${pos}, 0, ${q(JSON.stringify(config))});`,
    );

  view("grid", "Grid", "table", {}, 0);
  if (KANBAN[t.slug]) view("kanban", "Kanban", "kanban", { kanban: { stackFieldId: KANBAN[t.slug] } }, 1);
  if (CALENDAR[t.slug]) view("calendar", "Calendar", "calendar", { calendar: { dateFieldId: CALENDAR[t.slug] } }, 2);
  if (DASHBOARD[t.slug])
    view("dashboard", "Trends", "dashboard", { dashboard: DASHBOARD[t.slug], sorts: [{ fieldId: DASHBOARD[t.slug].dateFieldId, direction: "desc" }] }, 3);
});

// ---- a demo dashboard (workspace-level report composer over the CRM) -------
const DEALS_TID = "tbl_6b116201014a93e2";
const dashboardWidgets = [
  { widgetId: "wgt_pipeline", type: "kpi", title: "Pipeline value", tableId: DEALS_TID, agg: "sum", metricFieldId: "fld_32535ebf764c27b1" },
  { widgetId: "wgt_count", type: "kpi", title: "Open deals", tableId: DEALS_TID, agg: "count" },
  { widgetId: "wgt_by_stage", type: "bar", title: "Deals by stage", tableId: DEALS_TID, agg: "count", groupByFieldId: "fld_ab8460da74d9c748" },
  { widgetId: "wgt_over_time", type: "line", title: "Amount by month", tableId: DEALS_TID, agg: "sum", metricFieldId: "fld_32535ebf764c27b1", groupByFieldId: "fld_6f0bae1cf3cda9f7", bucket: "month" },
  { widgetId: "wgt_recent", type: "table", title: "Deals", tableId: DEALS_TID, fieldIds: ["fld_72fbfcec5a293bb7", "fld_32535ebf764c27b1", "fld_ab8460da74d9c748"] },
];
out.push(
  "INSERT OR REPLACE INTO meta_dashboards (dashboard_id, workspace_id, name, position, is_hidden, config) " +
    `VALUES ('dsh_demo_pipeline', NULL, 'Sales pipeline', 0, 0, ${q(JSON.stringify({ widgets: dashboardWidgets }))});`,
);

// ---- demo data -----------------------------------------------------------
// Fixed record ids so the seed is idempotent and the relation edges line up.
const COMPANIES = [
  { id: "rec_co_acme", name: "Acme Robotics", website: "https://acme.example", industry: "Manufacturing", employees: 320, status: "Active", notes: "Key account, multi-year contract." },
  { id: "rec_co_globex", name: "Globex SaaS", website: "https://globex.example", industry: "SaaS", employees: 85, status: "Lead", notes: "Inbound from webinar." },
  { id: "rec_co_initech", name: "Initech Health", website: "https://initech.example", industry: "Healthcare", employees: 540, status: "Active", notes: "Expansion opportunity in Q3." },
  { id: "rec_co_umbrella", name: "Umbrella Retail", website: "https://umbrella.example", industry: "Retail", employees: 1200, status: "Churned", notes: "Lost on price last cycle." },
];

const CONTACTS = [
  { id: "rec_ct_jordan", name: "Jordan Lee", email: "jordan@acme.example", title: "VP Engineering", company: "rec_co_acme" },
  { id: "rec_ct_sam", name: "Sam Rivera", email: "sam@globex.example", title: "Founder", company: "rec_co_globex" },
  { id: "rec_ct_priya", name: "Priya Nair", email: "priya@initech.example", title: "Director of IT", company: "rec_co_initech" },
  { id: "rec_ct_chris", name: "Chris Doyle", email: "chris@umbrella.example", title: "Procurement Lead", company: "rec_co_umbrella" },
];

const DEALS = [
  { id: "rec_dl_1", name: "Acme — Platform license", amount: 180000, stage: "Qualified", probability: 0.6, close_date: "2026-07-15", company: "rec_co_acme", owner: "Dana" },
  { id: "rec_dl_2", name: "Globex — Pilot", amount: 18000, stage: "New", probability: 0.2, close_date: "2026-06-30", company: "rec_co_globex", owner: "Dana" },
  { id: "rec_dl_3", name: "Initech — Expansion", amount: 64000, stage: "Won", probability: 1, close_date: "2026-05-20", company: "rec_co_initech", owner: "Morgan" },
  { id: "rec_dl_4", name: "Umbrella — Renewal", amount: 42000, stage: "Lost", probability: 0, close_date: "2026-04-01", company: "rec_co_umbrella", owner: "Morgan" },
];

out.push("\n-- demo rows");
for (const c of COMPANIES) {
  out.push(
    `INSERT OR REPLACE INTO companies (id, name, website, industry, employees, status, notes) ` +
      `VALUES (${q(c.id)}, ${q(c.name)}, ${q(c.website)}, ${q(c.industry)}, ${c.employees}, ${q(c.status)}, ${q(c.notes)});`,
  );
}
for (const c of CONTACTS) {
  out.push(
    `INSERT OR REPLACE INTO contacts (id, name, email, title) ` +
      `VALUES (${q(c.id)}, ${q(c.name)}, ${q(c.email)}, ${q(c.title)});`,
  );
  out.push(
    `INSERT OR REPLACE INTO link_company_contacts (company_id, contact_id) VALUES (${q(c.company)}, ${q(c.id)});`,
  );
}
for (const d of DEALS) {
  out.push(
    `INSERT OR REPLACE INTO deals (id, name, amount, stage, probability, close_date, owner) ` +
      `VALUES (${q(d.id)}, ${q(d.name)}, ${d.amount}, ${q(d.stage)}, ${d.probability}, ${q(d.close_date)}, ${q(d.owner)});`,
  );
  out.push(
    `INSERT OR REPLACE INTO link_company_deals (company_id, deal_id) VALUES (${q(d.company)}, ${q(d.id)});`,
  );
}

console.log(out.join("\n"));
console.error(`Seeded ${TABLES.length} tables + fields + views, ${COMPANIES.length} companies, ${CONTACTS.length} contacts, ${DEALS.length} deals`);
